// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clima": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "return the result of the weather for a specific day.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Especific day",
                        "name": "dia",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/weather.DayResult"
                        }
                    },
                    "400": {}
                }
            }
        },
        "/weather": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "return results of weather in JSON format.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/planet.WeatherResult"
                            }
                        }
                    },
                    "400": {}
                }
            }
        }
    },
    "definitions": {
        "planet.WeatherResult": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                },
                "weather": {
                    "type": "string"
                }
            }
        },
        "weather.DayResult": {
            "type": "object",
            "properties": {
                "clima": {
                    "type": "string"
                },
                "dia": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8084",
	BasePath:    "/",
	Schemes:     []string{"http"},
	Title:       "Sistema Solar",
	Description: "API to get the weather of the planets in the futures 10 years.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
